config/routes.rb
PdfGemTest::Application.routes.draw do
   root 'home#index'

   resources :home, only: [ :index, :new ] 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end

  def new
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf => "1",
        template: 'templates/test.pdf.haml'
      end
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.haml
= link_to 'generate PDF', "#{new_home_path}.pdf"

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PdfGemTest</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/templates/test.pdf.haml
.container
  %h1 Hello World :)
  %p
    Wicked PDF uses the shell utility wkhtmltopdf to serve a PDF file to a user from HTML. 
    In other words, rather than dealing with a PDF generation DSL of some sort, you simply 
    write an HTML view as you would normally, then let Wicked take care of the hard stuff.
    Wicked PDF has been verified to work on Ruby 1.8.7 and 1.9.2; Rails 2 and Rails 3